const { add } = require("./math");

function createHeader(text) {
  return `<h1>${text} <span id="result">0</span></h1>`;
}

function createParagraph(text) {
  return `<p>${text}</p>
  <form id="calc-form" action="#" method="get">
    <input type="text" name="q" placeholder="Search Google">
    <input type="number" name="calc" placeholder="Calculate" value="0">
    <input type="number" name="calc2" placeholder="Calculate" value="0">
    <button type="submit">Add numbers</button>
  </form>`;
}

function attachCalculator() {
  const form = document.getElementById("calc-form");
  const resultEl = document.getElementById("result");
  if (!form || !resultEl) return;

  const calc1 = form.querySelector('input[name="calc"]');
  const calc2 = form.querySelector('input[name="calc2"]');

  const updateResult = () => {
    const a = Number(calc1?.value) || 0;
    const b = Number(calc2?.value) || 0;
    resultEl.textContent = String(add(a, b));
  };

  form.addEventListener("submit", (e) => {
    e.preventDefault();
    updateResult();
  });
}

function createList(items) {
  const lis = items.map((item) => `<li>${item}</li>`).join("");
  return `<ul>${lis}</ul>`;
}

function generateHTML() {
  const header = createHeader("Hello Webpack!");
  const paragraph = createParagraph("This is a dummy page generated by JavaScript.");
  const list = createList(["Item 1", "Item 2", "Item 3"]);

  return `
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <title>Dummy Page</title>
</head>
<body>
  ${header}
  ${paragraph}
  ${list}
</body>
</html>`.trim();
}

module.exports = {
  createHeader,
  createParagraph,
  createList,
  generateHTML,
  attachCalculator,
};
