const { createHeader, createParagraph, createList, attachCalculator } = require("./app.js");

const root = document.getElementById("root");
root.innerHTML = [
  createHeader("Hello Webpack!"),
  createParagraph("This is a dummy page generated by JavaScript."),
  createList(["Item 1", "Item 2", "Item 3"]),
].join("");

attachCalculator();
